[theme]
primaryColor = "#5374a5"        # 按钮、链接、强调色
backgroundColor = "#ffffff"     # 主背景
secondaryBackgroundColor = "#f5f5f5"  # 侧边栏、卡片背景
textColor = "#31333F"           # 文字颜色
font = "sans serif"             # 字体
