[theme]
primaryColor = "#5374a5"        # 按钮、链接、强调色
backgroundColor = "#edf8ff"     # 主背景
secondaryBackgroundColor = "#e9f4ff"  # 侧边栏、卡片背景
textColor = "#31333F"           # 文字颜色
font = "sans serif"             # 字体
